POST http://localhost:8080/developer
Content-Type: application/json

{
  "memberId": "dog_gg",
  "developerType": "BACK_END",
  "developerLevel": "JUNIOR",
  "experienceYears": 1,
  "name": "mongmong",
  "age": "33"
}